### ISSUE TITLE
Sending message with notification key doesn't work

### ISSUE THREAD

**Issue by peterOnePageCRM** [spacialdb/gcm#17]
A message sent in this format as documented in the readme doesn't work:
     
    response = gcm.send([], {
            notification_key: "appUser-Chris-key",
            data: {score: "3x1"},
            collapse_key: "updated_score"})

**Comment by kashif** [comment]
ah great, you tried it out :bomb: can you let me know how you set it up so I can debug this?

**Comment by peterOnePageCRM** [comment]
@kashif what do you mean how I set it up?
Check out my pull request. Let me know what you think.
