### ISSUE TITLE
Sending images/ bidirectional messages.

### ISSUE THREAD

**Issue by moyinho20** [spacialdb/gcm#23]
I've used this gem for sending simple messages to single and multiple android devices and it worked like a charm. Great Work guys!
I was wondering though, what do I do for sending upstream messages, from device to app-servers? 
Also, how to send rich notifications? Mostly images are what I have in mind.

**Comment by kashif** [comment]
Thanks @moyinho20 for your kind words! :smiley_cat: 

For sending messages from device to the app server, you need to use the xmpp protocol and have that running on the ruby/rails side. I havent found a good xmpp server implementation for rails/ruby (let me know if there is one) and so we do not support that at the moment.

Hmm the gcm protocol has a 4Kb message limit, so its not really for sending images, and an idea might be to use gcm to send a message for a new image and its url and then your app downloads it...

Hope that helps!

**Comment by moyinho20** [comment]
I was thinking the same. Good that now you've confirmed. Thanks!
