### ISSUE TITLE
Response

### ISSUE THREAD

**Issue by wonderer007** [spacialdb/gcm#24]
I am getting this message in my response
"Only applies for JSON requests. Indicates that the request could not be parsed as JSON, or it contained invalid fields." 
Can you please help me out my code is 
GCM_CONNECTION.send(gcm_id, {sucess: true})

**Comment by NatalyTurlevsky** [comment]
I had the same issue when trying to send a big batch for 1000 devices.

**Comment by wonderer007** [comment]
actually i noticed that the json i am sending is causing issue.  If you follow exact same pattern of json as in options in following code 

require 'gcm'

gcm = GCM.new("my_api_key")
# you can set option parameters in here
#  - all options are pass to HTTParty method arguments
#  - ref: https://github.com/jnunemaker/httparty/blob/master/lib/httparty.rb#L40-L68
#  gcm = GCM.new("my_api_key", timeout: 3)

registration_ids= ["12", "13"] # an array of one or more client registration IDs
options = {data: {score: "123"}, collapse_key: "updated_score"}
response = gcm.send(registration_ids, options)


it works OK
