### ISSUE TITLE
Sending silent push notifications

### ISSUE THREAD

**Issue by davidtlee** [spacialdb/gcm#26]
Hi, sorry if this question is stupid, but I was wondering whether there's a way to send silent push notifications and how to do so.

Also, is there a place to read documentation on how to use this gem? I'm guessing my question is simple, but couldn't find it in the readme. Thanks!

**Comment by kashif** [comment]
@davidtlee what do you mean by silent push notifications? a push without any data?

**Comment by davidtlee** [comment]
I mean sending a push notification without having it vibrate the phone or make a sound (I just want it to show the text on the phone). For example, if I'm sending a push notification at 4AM in the morning to give them information for the upcoming day, I don't want that to make noise and accidentally wake them up.

**Comment by JWesorick** [comment]
+1

**Comment by kashif** [comment]
@davidtlee @JWesorick correct me if I am wrong, but isnt that logic implemented in the app itself rather than this gem? or is there some gcm flag that allows silent push notifications?

**Comment by davidtlee** [comment]
@kashif To be honest, I'm not sure. It seems to me that the backend that's sending out the push notification should be able to specify whether it's silent or not?
