### ISSUE TITLE
How to send messages to a topic?

### ISSUE THREAD

**Issue by emaillenin** [spacialdb/gcm#28]
As mentioned here - https://developers.google.com/cloud-messaging/topic-messaging

**Comment by GTkonfortes** [comment]
no gem support for sending messages to topics?

**Comment by alwaysanirudh** [comment]
I have done some modifications to handle topics.
https://github.com/spacialdb/gcm/pull/33

**Comment by mangar** [comment]
Hey.
I've forked and implemented it. There are some documentation on readme.
Hope it can help you as helped me. (https://github.com/mangar/gcm)

gcm = GCM.new("my_api_key")
options = {data: {title: "Title", message:"Message"}}    
gcm.send_topic("TOPIC_NAME", options)

**Comment by alwaysanirudh** [comment]
You can use it as follows:
```
    gcm = GCM.new("my_api_key")
    options = {data: {title: "Title", message:"Message"}}
    response = gcm.send("TOPIC_NAME", options, 'topics')
```
